# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000 # 30 hrs
  weight: 10
  startingGear: CMOGear
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  whitelistedSpecies:
    - Human
    - Felinid
  canBeAntag: true
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
    underwearb: ClothingUnderwearBottomBoxersCMO # White-Underwear
  underweart: ClothingUnderwearTopBraCMO # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesCMO # White-Underwear
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled
