using Content.Client.Message;
using Content.Shared.White.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.White.Economy.Ui;

[GenerateTypedNameReferences]
public sealed partial class BankUiFragment : BoxContainer
{
    public BankUiFragment()
    {
        RobustXamlLoader.Load(this);
    }
    public void UpdateState(BankCartridgeUiState state)
    {
        LinkedAccount.Visible = state.AccountLinked;
        NoLinkedAccountLabel.Visible = !state.AccountLinked;

        if (state.AccountLinked)
        {
            LinkedAccountNameLabel.SetMarkup(Loc.GetString("eftpos-ui-account-text", ("owner", state.OwnerName)));
            LinkedAccountBalanceLabel.SetMarkup(Loc.GetString("atm-ui-balance", ("balance", state.Balance)));
            return;
        }

        NoLinkedAccountLabel.SetMarkup(Loc.GetString("bank-program-ui-no-account"));
    }
}
