- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000
    - !type:OverallPlaytimeRequirement
      time: 108000
  weight: 20
  startingGear: CaptainGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
  whitelistedSpecies:
    - Human
    - Felinid
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    underwearb: ClothingUnderwearBottomBoxersCap # White-Underwear
  underweart: ClothingUnderwearTopBraCap # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesCap # White-Underwear
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
