using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private readonly IClientAdminManager _clientAdminManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-network"));
            Tabs.SetTabTitle(4, "Админ");
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            Tabs.SetTabVisible(4, _clientAdminManager.IsActive());
            base.FrameUpdate(args);
        }
    }
}
