- type: job
  id: MedicalCyborg
  name: medical-borg
  description: MedicalCyborg
  playTimeTracker: JobMedicalDoctor
  startingGear: MedicalCyborgGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  icon: "MedicalDoctor"
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgMedicalBattery
  canBeAntag: false

- type: job
  id: SecurityCyborg
  name: security-borg
  description: SecurityCyborg
  playTimeTracker: JobSecurityOfficer
  startingGear: SecurityCyborgGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgSecurityBattery
  canBeAntag: false
  icon: SecurityOfficer

- type: job
  id: EngineerCyborg
  name: engineer-borg
  description: EngineerCyborg
  playTimeTracker: JobStationEngineer
  startingGear: EngineerCyborgGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgEngBattery
  canBeAntag: false
  icon: StationEngineer

- type: job
  id: NekoCyborg
  name: neko-borg
  description: NekoCyborg
  playTimeTracker: JobServiceWorker
  startingGear: NekoCyborgGear
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10000
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgNekoBattery
  canBeAntag: false
  icon: Bartender

- type: job
  id: MinerCyborg
  name: miner-borg
  description: MinerCyborg
  playTimeTracker: JobSalvageSpecialist
  startingGear: MinerCyborgGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hrs
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgMinerBattery
  canBeAntag: false
  icon: ShaftMiner

- type: job
  id: ClownCyborg
  name: clown-borg
  description: ClownCyborg
  playTimeTracker: JobClown
  startingGear: ClownCyborgGear
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10000
  supervisors: job-supervisors-human
  jobEntity: PlayerCyborgClownBattery
  canBeAntag: false
  icon: Clown


# ёбанный костыль! Чтобы борги отображались при выборе профессии..

- type: startingGear
  id: MedicalCyborgGear
  equipment:
    outerClothing: ClothingIconMedicalCyborg

- type: startingGear
  id: SecurityCyborgGear
  equipment:
    outerClothing: ClothingIconSecurityCyborgGear

- type: startingGear
  id: EngineerCyborgGear
  equipment:
    outerClothing: ClothingIconEngineerCyborgGear

- type: startingGear
  id: NekoCyborgGear
  equipment:
    outerClothing: ClothingIconNekoCyborgGear

- type: startingGear
  id: ClownCyborgGear
  equipment:
    outerClothing: ClothingIconClownCyborgGear

- type: startingGear
  id: MinerCyborgGear
  equipment:
    outerClothing: ClothingIconMinerCyborgGear


- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconMedicalCyborg
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_medical.rsi
      layers:
        - state: robot
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_medical.rsi
      equippedState: robot

- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconSecurityCyborgGear
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_sec.rsi
      layers:
        - state: robot
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_sec.rsi
      equippedState: robot

- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconEngineerCyborgGear
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_eng.rsi
      layers:
        - state: robot
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_eng.rsi
      equippedState: robot

- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconNekoCyborgGear
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_kerfus.rsi
      layers:
        - state: kerfusNT
        - state: eyes-kerfusNT
          shader: unshaded
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_kerfus.rsi
      equippedState: kerfusNT

- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconClownCyborgGear
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_clown.rsi
      layers:
        - state: clown
        - state: clown_e_r
          shader: unshaded
        - state: clown_l
          shader: unshaded
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_clown.rsi
      equippedState: clown

- type: entity
  parent: ClothingOuterBaseLarge
  id: ClothingIconMinerCyborgGear
  name: meow
  description: mew
  components:
    - type: HumanHide
    - type: Sprite
      sprite: White/Mobs/Player/Borgs/cyborg_miner.rsi
      layers:
        - state: minerOLD
        - state: miner_e
          shader: unshaded
    - type: Clothing
      sprite: White/Mobs/Player/Borgs/cyborg_miner.rsi
      equippedState: minerOLD
