- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 54000 # 15 hours
  startingGear: DetectiveGear
  icon: "Detective"
  supervisors: job-supervisors-hos
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
  whitelistedSpecies:
    - Human
    - Dwarf
    - Felinid
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    outerClothing: ClothingOuterVestDetective
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    pocket1: ForensicPad
    pocket2: ForensicScanner
    belt: ClothingBeltHolster
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraSportsAlternative # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  innerclothingskirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
