- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 86400 # 24 hrs
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 43200 # 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 720000 # 200 hrs
  startingGear: SeniorOfficerGear
  icon: "SeniorOfficer"
  supervisors: job-supervisors-hos
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
  whitelistedSpecies:
    - Human
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Medical

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorOfficer
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeret
    outerClothing: ClothingOuterArmorBasic
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSeniorSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: MagazinePistol
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckSecuritymedal
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  innerclothingskirt: ClothingUniformJumpskirtSeniorOfficer
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
