- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
  icon: "ShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
