using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Utility;

namespace Content.Client.White.CriminalRecords.UI.Controls;

[GenerateTypedNameReferences, Virtual]
public partial class RecordIconButton : Control
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public string Icon
    {
        set
        {
            var path = new ResPath(value); // /Textures/Interface/VerbIcons/close.svg.192dpi.png
            var specifier = new SpriteSpecifier.Texture(path);
            LIcon.Texture = specifier.Frame0();
        }
    }

    public string Label
    {
        set => LLabel.SetMessage(value);
    }

    public RecordIconButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
