using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.White.SinguloCall;

[GenerateTypedNameReferences]
public sealed partial class SinguloCall : DefaultWindow
{
    public Action<string>? OnNameChange;

    public SinguloCall()
    {
        RobustXamlLoader.Load(this);

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange!(NameSelector.Text);
        };
    }

    public void UpdateState(string name)
    {
        NameSelector.Text = name;
    }
}
