using Content.Shared.White.Cyborg.CyborgSensor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.White.Cyborg.CyborgConsole;

[GenerateTypedNameReferences]
public sealed partial class CyborgConsoleUnitContainer : PanelContainer
{
    public CyborgConsoleUnitContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetView(string icon)
    {
        BorgRect.TexturePath = icon;
    }

    public void SetTitle(string text)
    {
        Title.Text = text;
    }

    public void OnButtonPressed(Action<BaseButton.ButtonEventArgs> func)
    {
        Select.OnPressed += func;
    }
}
