using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.White.Cyborg.CyborgConsole;

[GenerateTypedNameReferences]
public sealed partial class CyborgConsoleLawsControlContainer : PanelContainer
{
    public CyborgConsoleLawsControlContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTitle(string title)
    {
        Title.Text = title;
    }

    public void SetDescription(string description)
    {
        var fw = new FormattedMessage();
        fw.AddText(description);
        Description.SetMessage(fw);
    }

    public void OnRaiseClicked(Action<BaseButton.ButtonEventArgs> func)
    {
        UpLaw.Pressed = false;
        UpLaw.OnPressed += func;
    }
    public void OnLowClicked(Action<BaseButton.ButtonEventArgs> func)
    {
        DownLaw.Pressed = false;
        DownLaw.OnPressed += func;
    }
    public void OnRemoveClicked(Action<BaseButton.ButtonEventArgs> func)
    {
        RemoveLaw.OnPressed += func;
    }
}
