using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.White.Cyborg.InstrumentSelect;

[GenerateTypedNameReferences]
public sealed partial class CyborgInstrumentSelectContainer : PanelContainer
{
    public CyborgInstrumentSelectContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetLabel(string text)
    {
        InstrumentLabel.Text = text;
    }

    public void SetView(EntityUid uid)
    {
        InstrumentView.SetEntity(uid);
    }

    public void OnButtonPressed(Action<BaseButton.ButtonEventArgs> func)
    {
        Select.OnPressed += func;
    }


}
