using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Timing;

namespace Content.Client.White.UserInterface.Controls;

[GenerateTypedNameReferences, Virtual, PublicAPI]
public sealed partial class RadialButton : Control
{
    [Animatable] public Vector2 Offset { get; set; }
    public string? Content { get; set; }

    public string Texture
    {
        set => Controller.TexturePath = value;
    }

    [Animatable]
    public Vector2 ButtonSize
    {
        get => this.Size;
        set => this.SetSize = value;
    }

    public RadialButton()
    {
        RobustXamlLoader.Load(this);
        Offset = Vector2.Zero;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
    }
}
