using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.White.Rules;

[GenerateTypedNameReferences]
public sealed partial class RulesWikiSection : BoxContainer
{
    public RulesWikiSection()
    {
        RobustXamlLoader.Load(this);
    }
}
