using Content.Shared.White;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.White.Rules;

[GenerateTypedNameReferences]
public sealed partial class RulesWikiSection : BoxContainer
{
    [Dependency] private readonly IUriOpener _uri = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public RulesWikiSection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RulesButton.OnPressed += _ => _uri.OpenUri(_cfg.GetCVar(WhiteCVars.RulesWiki));
    }
}
